# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialogedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(328, 301)
        self.widgCustomer = QtWidgets.QWidget(Dialog)
        self.widgCustomer.setGeometry(QtCore.QRect(0, 0, 401, 211))
        self.widgCustomer.setObjectName("widgCustomer")
        self.widgCustomer.setVisible(False)
        self.lineCompany = QtWidgets.QLineEdit(self.widgCustomer)
        self.lineCompany.setGeometry(QtCore.QRect(120, 40, 113, 21))
        self.lineCompany.setObjectName("lineCompany")
        self.label_2 = QtWidgets.QLabel(self.widgCustomer)
        self.label_2.setGeometry(QtCore.QRect(80, 70, 61, 16))
        self.label_2.setObjectName("label_2")
        self.linePhone = QtWidgets.QLineEdit(self.widgCustomer)
        self.linePhone.setGeometry(QtCore.QRect(120, 90, 113, 22))
        self.linePhone.setObjectName("linePhone")
        self.label = QtWidgets.QLabel(self.widgCustomer)
        self.label.setGeometry(QtCore.QRect(80, 20, 61, 16))
        self.label.setObjectName("label")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(180, 240, 93, 28))
        self.btnCancel.setObjectName("btnCancel")
        self.btnEdit = QtWidgets.QPushButton(Dialog)
        self.btnEdit.setGeometry(QtCore.QRect(60, 240, 93, 28))
        self.btnEdit.setObjectName("btnEdit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 280, 301, 16))
        self.label_3.setObjectName("label_3")
        self.widgetAddIng = QtWidgets.QWidget(Dialog)
        self.widgetAddIng.setGeometry(QtCore.QRect(0, 0, 331, 151))
        self.widgetAddIng.setObjectName("widgetAddIng")
        self.widgetAddIng.setVisible(False)
        self.label_6 = QtWidgets.QLabel(self.widgetAddIng)
        self.label_6.setGeometry(QtCore.QRect(60, 20, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widgetAddIng)
        self.label_7.setGeometry(QtCore.QRect(60, 70, 55, 16))
        self.label_7.setObjectName("label_7")
        self.lineIngName = QtWidgets.QLineEdit(self.widgetAddIng)
        self.lineIngName.setGeometry(QtCore.QRect(60, 40, 113, 22))
        self.lineIngName.setObjectName("lineIngName")
        self.lineIngPrice = QtWidgets.QLineEdit(self.widgetAddIng)
        self.lineIngPrice.setGeometry(QtCore.QRect(60, 90, 113, 22))
        self.lineIngPrice.setObjectName("lineIngPrice")
        self.label_8 = QtWidgets.QLabel(self.widgetAddIng)
        self.label_8.setGeometry(QtCore.QRect(190, 20, 91, 16))
        self.label_8.setObjectName("label_8")
        self.lineIngInfo = QtWidgets.QLineEdit(self.widgetAddIng)
        self.lineIngInfo.setGeometry(QtCore.QRect(190, 40, 113, 22))
        self.lineIngInfo.setObjectName("lineIngInfo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Телефон"))
        self.label.setText(_translate("Dialog", "Компания"))
        self.btnCancel.setText(_translate("Dialog", "Отмена"))
        self.btnEdit.setText(_translate("Dialog", "Изменить"))
        self.label_3.setText(_translate("Dialog", "Незаполненые поля сохраняют старое значение"))
        self.label_6.setText(_translate("Dialog", "Название"))
        self.label_7.setText(_translate("Dialog", "Цена"))
        self.label_8.setText(_translate("Dialog", "Информация"))
