# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialofDelete.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(231, 134)
        self.labelInfo = QtWidgets.QLabel(Dialog)
        self.labelInfo.setGeometry(QtCore.QRect(30, 30, 191, 20))
        self.labelInfo.setObjectName("labelInfo")
        self.btnYes = QtWidgets.QPushButton(Dialog)
        self.btnYes.setGeometry(QtCore.QRect(20, 70, 93, 28))
        self.btnYes.setObjectName("btnYes")
        self.btnNo = QtWidgets.QPushButton(Dialog)
        self.btnNo.setGeometry(QtCore.QRect(130, 70, 93, 28))
        self.btnNo.setObjectName("btnNo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelInfo.setText(_translate("Dialog", "Удалить "))
        self.btnYes.setText(_translate("Dialog", "Да"))
        self.btnNo.setText(_translate("Dialog", "Нет"))
