# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialohAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(335, 277)
        self.widgAddCustomer = QtWidgets.QWidget(Dialog)
        self.widgAddCustomer.setGeometry(QtCore.QRect(0, 0, 401, 151))
        self.widgAddCustomer.setObjectName("widgAddCustomer")
        self.widgAddCustomer.setVisible(False)
        self.lineCompany = QtWidgets.QLineEdit(self.widgAddCustomer)
        self.lineCompany.setGeometry(QtCore.QRect(70, 40, 113, 21))
        self.lineCompany.setObjectName("lineCompany")
        self.linePhone = QtWidgets.QLineEdit(self.widgAddCustomer)
        self.linePhone.setGeometry(QtCore.QRect(70, 90, 113, 22))
        self.linePhone.setObjectName("linePhone")
        self.label = QtWidgets.QLabel(self.widgAddCustomer)
        self.label.setGeometry(QtCore.QRect(30, 20, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widgAddCustomer)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 61, 16))
        self.label_2.setObjectName("label_2")
        self.btnAdd = QtWidgets.QPushButton(Dialog)
        self.btnAdd.setGeometry(QtCore.QRect(70, 230, 93, 28))
        self.btnAdd.setObjectName("btnAdd")
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(190, 230, 93, 28))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Компания"))
        self.label_2.setText(_translate("Dialog", "Телефон"))
        self.btnAdd.setText(_translate("Dialog", "Добавить"))
        self.btnCancel.setText(_translate("Dialog", "Отмена"))
