# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(205, 193)
        self.lineUser = QtWidgets.QLineEdit(Dialog)
        self.lineUser.setGeometry(QtCore.QRect(40, 40, 131, 21))
        self.lineUser.setObjectName("lineUser")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label.setObjectName("label")
        self.linePassword = QtWidgets.QLineEdit(Dialog)
        self.linePassword.setGeometry(QtCore.QRect(40, 100, 129, 22))
        self.linePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.linePassword.setObjectName("linePassword")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 55, 16))
        self.label_2.setObjectName("label_2")
        self.btnLogin = QtWidgets.QPushButton(Dialog)
        self.btnLogin.setGeometry(QtCore.QRect(60, 140, 93, 28))
        self.btnLogin.setObjectName("btnLogin")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Пользователь:"))
        self.label_2.setText(_translate("Dialog", "Пароль:"))
        self.btnLogin.setText(_translate("Dialog", "Вход"))


