# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.Dicts = QtWidgets.QMenu(self.menubar)
        self.Dicts.setObjectName("Dicts")
        self.Orders = QtWidgets.QMenu(self.menubar)
        self.Orders.setObjectName("Orders")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Ings = QtWidgets.QAction(MainWindow)
        self.Ings.setObjectName("Ings")
        self.Products = QtWidgets.QAction(MainWindow)
        self.Products.setObjectName("Products")
        self.Customers = QtWidgets.QAction(MainWindow)
        self.Customers.setObjectName("Customers")
        self.Dicts.addAction(self.Ings)
        self.Dicts.addAction(self.Products)
        self.Dicts.addAction(self.Customers)
        self.menubar.addAction(self.Dicts.menuAction())
        self.menubar.addAction(self.Orders.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Dicts.setTitle(_translate("MainWindow", "Справочники"))
        self.Orders.setTitle(_translate("MainWindow", "Заказы"))
        self.Ings.setText(_translate("MainWindow", "Ингридиенты"))
        self.Products.setText(_translate("MainWindow", "Продукты"))
        self.Customers.setText(_translate("MainWindow", "Заказчики"))
