# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnTest = QtWidgets.QPushButton(self.centralwidget)
        self.btnTest.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.btnTest.setObjectName("btnTest")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 50, 791, 501))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(250, 10, 31, 31))
        self.btnBack.setObjectName("btnBack")
        self.btnTop5 = QtWidgets.QPushButton(self.centralwidget)
        self.btnTop5.setGeometry(QtCore.QRect(110, 10, 121, 28))
        self.btnTop5.setObjectName("btnTop5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Ings = QtWidgets.QAction(MainWindow)
        self.Ings.setObjectName("Ings")
        self.Products = QtWidgets.QAction(MainWindow)
        self.Products.setObjectName("Products")
        self.Customers = QtWidgets.QAction(MainWindow)
        self.Customers.setObjectName("Customers")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnTest.setText(_translate("MainWindow", "PushButton"))
        self.btnBack.setText(_translate("MainWindow", "<-"))
        self.btnTop5.setText(_translate("MainWindow", "Топ5 по месяцам"))
        self.Ings.setText(_translate("MainWindow", "Ингридиенты"))
        self.Products.setText(_translate("MainWindow", "Продукты"))
        self.Customers.setText(_translate("MainWindow", "Заказчики"))
